Repository moevm/nosql1h25-electronics, pull requests merged in 2025-04, with the labels that each got.

#9 feat: create frontend project
  frontend/.editorconfig
  frontend/.gitignore
  frontend/eslint.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App.module.css
  frontend/src/components/App.tsx
  frontend/src/main.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.vite.json
  frontend/vite.config.ts
Labels: enhancement

#14 feat: add routing
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App.tsx
  frontend/src/components/pages/NotFoundPage.tsx
  frontend/src/components/pages/TestPage.tsx
  frontend/src/routes/Routes.tsx
Labels: enhancement

#16 feat: create login, register and requests pages
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/App.module.css
  frontend/src/components/App.tsx
  frontend/src/components/pages/LoginPage/LoginPage.module.css
  frontend/src/components/pages/LoginPage/LoginPage.tsx
  frontend/src/components/pages/RegisterPage/RegisterPage.module.css
  frontend/src/components/pages/RegisterPage/RegisterPage.tsx
  frontend/src/components/pages/RequestsAdminPage.tsx
  frontend/src/components/pages/RequestsClientPage.tsx
  frontend/src/components/themes/smallInputs.ts
  frontend/src/components/ui/FormFields.tsx
  frontend/src/components/ui/PasswordField.tsx
  frontend/src/components/ui/RequestsTable.tsx
  frontend/src/lib/russianConverters.ts
  frontend/src/lib/typeUtility.ts
  frontend/src/main.tsx
  frontend/src/model/category.ts
  frontend/src/model/data.example.ts
  frontend/src/model/misc.ts
  frontend/src/model/request.ts
  frontend/src/model/status.ts
  frontend/src/model/user.ts
  frontend/src/routes/Routes.tsx
  frontend/tsconfig.app.json
  frontend/vite.config.ts
Labels: enhancement

#17 feat: add requests api
  backend/api/models.py
  backend/api/serializers.py
  backend/api/urls.py
  backend/api/views.py
  backend/electronics/urls.py
  backend/requirements.txt
Labels: enhancement

#20 fix: change filename
  frontend/src/components/themes/SmallInputs.ts
Labels: enhancement

#21 fix: add minor changes to backend
  backend/README.md
  backend/electronics/settings.py
Labels: enhancement

#15 feat: add product card page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pages/ProductCardPage.tsx
  frontend/src/components/pages/ProductCreateDialogExample.tsx
  frontend/src/components/ui/ImageGallery.module.css
  frontend/src/components/ui/ImageGallery.tsx
  frontend/src/components/ui/Loader.tsx
  frontend/src/components/ui/ProductCreateDialog.tsx
  frontend/src/components/ui/ProductTimeline.tsx
  frontend/src/main.tsx
  frontend/src/routes/Routes.tsx
Labels: enhancement

#22 fix: update backup methods
  backend/api/views.py
Labels: enhancement

#23 feat: add swagger support
  frontend/generate-api.ps1
  frontend/generate-api.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/schema.json
  frontend/src/api/apiClient.ts
  frontend/src/api/core/ApiError.ts
  frontend/src/api/core/ApiRequestOptions.ts
  frontend/src/api/core/ApiResult.ts
  frontend/src/api/core/CancelablePromise.ts
  frontend/src/api/core/OpenAPI.ts
  frontend/src/api/core/request.ts
  frontend/src/api/index.ts
  frontend/src/api/middleware/errorInterceptor.ts
  frontend/src/api/middleware/forbiddenErrorInterceptor.ts
  frontend/src/api/middleware/requestInterceptor.ts
  frontend/src/api/middleware/responseInterceptor.ts
  frontend/src/api/models/CategoryEnum.ts
  frontend/src/api/models/CustomTokenObtainPair.ts
  frontend/src/api/models/ErrorResponse.ts
  frontend/src/api/models/PhotoResponse.ts
  frontend/src/api/models/Register.ts
  frontend/src/api/models/Request.ts
  frontend/src/api/models/TokenResponse.ts
  frontend/src/api/models/UserResponse.ts
  frontend/src/api/services/ApiService.ts
  frontend/src/api/services/AuthService.ts
Labels: enhancement

#24 feat: fix axios instance integration
  frontend/generate-api.sh
  frontend/package-lock.json
  frontend/package.json
  frontend/scripts/postgenerate.cjs
  frontend/src/api/core/request.ts
Labels: enhancement

#29 fix: fix api middleware
  frontend/src/api/apiClient.ts
  frontend/src/api/middleware/forbiddenErrorInterceptor.ts
  frontend/src/api/middleware/responseInterceptor.ts
Labels: enhancement

#25 feat: add redux toolkit
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pages/LoginPage/LoginPage.tsx
  frontend/src/components/pages/RequestsAdminPage.tsx
  frontend/src/components/pages/RequestsClientPage.tsx
  frontend/src/hooks/ReduxHooks.ts
  frontend/src/lib/Sleep.ts
  frontend/src/main.tsx
  frontend/src/routes/AdminOnly.tsx
  frontend/src/routes/AuthorizedOnly.tsx
  frontend/src/routes/ClientOnly.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/store/RequestsSlice.ts
  frontend/src/store/Store.ts
  frontend/src/store/UserSlice.ts
Labels: enhancement

#26 fix: rename api names
  backend/api/models.py
  backend/api/serializers.py
  backend/api/urls.py
  backend/api/views.py
  backend/electronics/settings.py
  backend/requirements.txt
Labels: enhancement

#30 fix: add register free search
  backend/api/views.py
Labels: bug

#31 feat: regenerate swagger api
  frontend/schema.json
  frontend/src/api/index.ts
  frontend/src/api/models/Photo.ts
  frontend/src/api/models/ProductRequest.ts
  frontend/src/api/services/ApiService.ts
Labels: enhancement

#32 fix: fix token lifetime
  backend/authapp/serializers.py
Labels: bug

#35 fix: add sort
  backend/api/urls.py
  backend/api/views.py
Labels: bug

#27 feat: add api to product card page
  backend/api/views.py
  backend/electronics/settings.py
  frontend/schema.json
  frontend/src/api/apiClient.ts
  frontend/src/api/index.ts
  frontend/src/api/models/Photo.ts
  frontend/src/api/services/ApiService.ts
  frontend/src/components/pages/ProductCardPage.tsx
  frontend/src/components/pages/RequestsAdminPage.tsx
  frontend/src/components/pages/RequestsClientPage.tsx
  frontend/src/components/pages/TestPage.tsx
  frontend/src/components/ui/ErrorMessage.tsx
  frontend/src/components/ui/ProductCreateDialog.tsx
  frontend/src/components/ui/ProductTimeline.tsx
  frontend/src/components/ui/RequestsTable.tsx
  frontend/src/lib/russianConverters.ts
  frontend/src/store/RequestsSlice.ts
  frontend/src/store/UserSlice.ts
Labels: enhancement

#34 feat: integrate api with login and requests pages
  frontend/package-lock.json
  frontend/package.json
  frontend/schema.json
  frontend/src/api/services/ApiService.ts
  frontend/src/components/pages/LoginPage/LoginPage.tsx
  frontend/src/components/pages/ProductCreateDialogExample.tsx
  frontend/src/components/pages/RegisterPage/RegisterPage.tsx
  frontend/src/components/pages/RequestsAdminPage.tsx
  frontend/src/components/pages/RequestsClientPage.tsx
  frontend/src/components/ui/RequestsTable.tsx
  frontend/src/model/category.ts
  frontend/src/model/data.example.ts
  frontend/src/model/request.ts
  frontend/src/model/status.ts
  frontend/src/model/user.ts
  frontend/src/routes/Routes.tsx
  frontend/src/store/RequestsSlice.ts
Labels: enhancement

#36 fix: update phone field at request response
  backend/api/serializers.py
Labels: bug

#37 feat: update backup with token version
  backend/api/views.py
Labels: enhancement

#38 fix: update permissions for photos
  backend/api/views.py
Labels: enhancement

#39 fix: fix bugs with gallery
  frontend/src/components/ui/ImageGallery.module.css
  frontend/src/components/ui/ImageGallery.tsx
Labels: bug

#40 feat: add docker for frontend
  backend/.dockerignore
  backend/Dockerfile
  backend/electronics/settings.py
  docker-compose.yml
  example.env
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/nginx.conf
  frontend/tsconfig.app.json
Labels: enhancement

#42 fix: fix github actions
  .env
Labels: enhancement

#43 Develop
  .env
Labels: enhancement

#44 docs: update docs with run instrucitons
  README.md
Labels: documentation

#47 fix: update CORS
  backend/electronics/settings.py
Labels: bug

#50 feat: update env fields
  .env
  README.md
  backend/README.md
  backend/electronics/settings.py
Labels: enhancement
