Repository moevm/nosql1h25-electronics, pull requests merged in 2025-05, with the labels that each got.

#48 feat: add status update method
  backend/api/models.py
  backend/api/serializers.py
  backend/api/urls.py
  backend/api/views.py
Labels: enhancement

#52 feat: get user by id
  backend/api/serializers.py
  backend/api/urls.py
  backend/api/views.py
Labels: enhancement

#58 fix: add timezone support
  backend/api/models.py
  backend/api/serializers.py
  backend/api/views.py
  backend/authapp/models.py
Labels: bug

#56 refactor: refactor frontend
  frontend/src/api/services/ApiService.ts
  frontend/src/components/pages/EditProfilePage.tsx
  frontend/src/components/pages/LoginPage.tsx
  frontend/src/components/pages/LoginPage/LoginPage.module.css
  frontend/src/components/pages/ProductCardPage.tsx
  frontend/src/components/pages/ProductsPage.tsx
  frontend/src/components/pages/RegisterPage.tsx
  frontend/src/components/pages/RegisterPage/RegisterPage.module.css
  frontend/src/components/pages/RequestsAdminPage.tsx
  frontend/src/components/pages/RequestsClientPage.tsx
  frontend/src/components/themes/SmallInputs.ts
  frontend/src/components/ui/AdminFilters.tsx
  frontend/src/components/ui/ClientFilters.tsx
  frontend/src/components/ui/FormFields.tsx
  frontend/src/components/ui/PasswordField.tsx
  frontend/src/components/ui/PhoneField.tsx
  frontend/src/components/ui/ProductCreateDialog.tsx
  frontend/src/components/ui/ProductsTable.tsx
  frontend/src/components/ui/RequestsTable.tsx
  frontend/src/components/ui/buttons/BackupExportButton.tsx
  frontend/src/components/ui/buttons/BackupImportButton.tsx
  frontend/src/components/ui/buttons/CreateProductButton.tsx
  frontend/src/components/ui/buttons/LogoutButton.tsx
  frontend/src/components/ui/form/CheckboxFormField.tsx
  frontend/src/components/ui/form/DateFormField.tsx
  frontend/src/components/ui/form/FormFieldPropsBase.ts
  frontend/src/components/ui/form/PasswordFormField.tsx
  frontend/src/components/ui/form/PhoneFormField.tsx
  frontend/src/components/ui/form/SelectFormField.tsx
  frontend/src/components/ui/form/TextFormField.tsx
  frontend/src/lib/RussianConverters.ts
  frontend/src/lib/Sleep.ts
  frontend/src/lib/russianConverters.ts
  frontend/src/lib/typeUtility.ts
  frontend/src/model/misc.ts
  frontend/src/routes/AdminOnly.tsx
  frontend/src/routes/AuthorizedOnly.tsx
  frontend/src/routes/ClientOnly.tsx
  frontend/src/routes/Routes.tsx
  frontend/src/store/ProductsSlice.ts
  frontend/src/store/Store.ts
  frontend/src/store/UserSlice.ts
Labels: enhancement

#55 feat: add timeline
  backend/api/views.py
  frontend/src/components/pages/ProductCardPage.tsx
  frontend/src/components/ui/ImageGallery.module.css
  frontend/src/components/ui/ImageGallery.tsx
  frontend/src/components/ui/ProductTimeline.tsx
  frontend/src/components/ui/timeline/ProductTimeline.tsx
  frontend/src/components/ui/timeline/inputs/AcceptDate.tsx
  frontend/src/components/ui/timeline/inputs/AcceptPrice.tsx
  frontend/src/components/ui/timeline/inputs/CloseRequest.tsx
  frontend/src/components/ui/timeline/inputs/DateInput.tsx
  frontend/src/components/ui/timeline/inputs/PriceInput.tsx
  frontend/src/components/ui/timeline/items/AfterCreatedItem.tsx
  frontend/src/components/ui/timeline/items/AfterPriceAccpetItem.tsx
  frontend/src/components/ui/timeline/items/DateOfferLoopItem.tsx
  frontend/src/components/ui/timeline/items/PreClosedStatusItem.tsx
  frontend/src/components/ui/timeline/items/PriceOfferLoopItem.tsx
  frontend/src/components/ui/timeline/items/PrimaryItem.tsx
  frontend/src/lib/TimelineItemUtility.tsx
  frontend/src/main.tsx
Labels: enhancement

#64 feat: add pagination backend
  backend/api/serializers.py
  backend/api/views.py
Labels: enhancement

#65 fix: fix swagger 200 response body
  backend/api/views.py
Labels: bug

#60 feat: add pagination
  backend/migrations/backup.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/index.ts
  frontend/src/api/models/ProductRequestListResponse.ts
  frontend/src/api/services/ApiService.ts
  frontend/src/components/pages/EditProfilePage.tsx
  frontend/src/components/pages/ProductCardPage.tsx
  frontend/src/components/pages/ProductsPage.tsx
  frontend/src/components/ui/ProductsTable.tsx
  frontend/src/components/ui/buttons/BackupImportButton.tsx
  frontend/src/components/ui/buttons/CreateProductButton.tsx
  frontend/src/components/ui/buttons/LogoutButton.tsx
  frontend/src/main.tsx
  frontend/src/store/ProductsSlice.ts
  frontend/src/store/Store.ts
Labels: enhancement

#66 fix: add if-else for list and queryset
  backend/api/views.py
Labels: bug

#63 feat: add statistics page
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/pages/ProductsPage.tsx
  frontend/src/components/pages/StatisticsPage.tsx
  frontend/src/routes/Routes.tsx
Labels: enhancement

#68 docs: add reports
  report.docx
  report.pdf
Labels: documentation

#69 docs/add users to readme
  README.md
Labels: documentation
